SET PAGESIZE 0;
UNDEFINE NEW_USER;
UNDEFINE CLONE_FROM_USER;
SET SERVEROUTPUT ON;
 
DECLARE
COUNT_CLONE_FROM_USER_ROLEPRIVIS NUMBER;
COUNT_NEW_USER_ROLEPRIVIS NUMBER;
COUNT_CLONE_FROM_USER_SYSPRIVIS NUMBER;
COUNT_NEW_USER_SYSPRIVIS NUMBER;
COUNT_CLONE_FROM_USER_TABPRIVIS NUMBER;
COUNT_NEW_USER_TABPRIVIS NUMBER;
 
BEGIN
 
 
SELECT COUNT(GRANTED_ROLE) INTO COUNT_CLONE_FROM_USER_ROLEPRIVIS FROM DBA_ROLE_PRIVS WHERE GRANTEE = UPPER('&&CLONE_FROM_USER');
SELECT COUNT(GRANTED_ROLE) INTO COUNT_NEW_USER_ROLEPRIVIS FROM DBA_ROLE_PRIVS WHERE GRANTEE = UPPER('&&NEW_USER');
SELECT COUNT(PRIVILEGE) INTO COUNT_CLONE_FROM_USER_SYSPRIVIS FROM DBA_SYS_PRIVS WHERE GRANTEE = UPPER('&&CLONE_FROM_USER');
SELECT COUNT(PRIVILEGE) INTO COUNT_NEW_USER_SYSPRIVIS FROM DBA_SYS_PRIVS WHERE GRANTEE = UPPER('&&NEW_USER'); 
SELECT COUNT(PRIVILEGE) INTO COUNT_CLONE_FROM_USER_TABPRIVIS FROM DBA_TAB_PRIVS WHERE GRANTEE = UPPER('&&CLONE_FROM_USER');
SELECT COUNT(PRIVILEGE) INTO COUNT_NEW_USER_TABPRIVIS FROM DBA_TAB_PRIVS WHERE GRANTEE = UPPER('&&NEW_USER');
 
IF (COUNT_CLONE_FROM_USER_ROLEPRIVIS <= COUNT_NEW_USER_ROLEPRIVIS AND COUNT_CLONE_FROM_USER_SYSPRIVIS <= COUNT_NEW_USER_SYSPRIVIS AND COUNT_CLONE_FROM_USER_TABPRIVIS <= COUNT_NEW_USER_TABPRIVIS)
 
THEN
 
DBMS_OUTPUT.PUT_LINE('----------------');
DBMS_OUTPUT.PUT_LINE('GRANT SUCCESSFUL');
DBMS_OUTPUT.PUT_LINE('----------------');
 
ELSE
 
 
DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
DBMS_OUTPUT.PUT_LINE('GRANT UNSUCCESSFUL IN CHECKS GRANT THE FOLLOWING PERMISSIONS');
DBMS_OUTPUT.PUT_LINE('------------------------------------------------------------');
 
 
FOR DRP IN (SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE=UPPER('&&CLONE_FROM_USER') MINUS SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS WHERE GRANTEE=UPPER('&&NEW_USER'))
LOOP
DBMS_OUTPUT.PUT_LINE('GRANT '||DRP.GRANTED_ROLE||' TO &&NEW_USER;');
END LOOP;
 
FOR DSP IN (SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE=UPPER('&&CLONE_FROM_USER') MINUS SELECT PRIVILEGE FROM DBA_SYS_PRIVS WHERE GRANTEE=UPPER('&&NEW_USER'))
LOOP
DBMS_OUTPUT.PUT_LINE('GRANT '||DSP.PRIVILEGE||' TO &&NEW_USER;');
END LOOP;
 
FOR DTP IN (SELECT PRIVILEGE,OWNER,TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE IN UPPER('&&CLONE_FROM_USER') MINUS SELECT PRIVILEGE,OWNER,TABLE_NAME FROM DBA_TAB_PRIVS WHERE GRANTEE IN UPPER('&&NEW_USER'))
LOOP
DBMS_OUTPUT.PUT_LINE('GRANT '||DTP.PRIVILEGE||' ON '||DTP.OWNER||'.'||DTP.TABLE_NAME||' TO &&NEW_USER;');
END LOOP;
END IF;
 
END;
 
/
